// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: envoy/config/etcd/v3/etcd_cluster.proto

package envoy_config_etcd_v3

import (
	v3 "envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "udpa/annotations"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Rate limit :ref:`configuration overview <config_etcd_service>`.
type EtcdServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Specifies the gRPC service that hosts the etcd cluster. The client
	// will connect to this cluster when it needs to make watch
	// requests.
	GrpcService *v3.GrpcService `protobuf:"bytes,1,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
}

func (x *EtcdServiceConfig) Reset() {
	*x = EtcdServiceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_config_etcd_v3_etcd_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EtcdServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdServiceConfig) ProtoMessage() {}

func (x *EtcdServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_config_etcd_v3_etcd_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdServiceConfig.ProtoReflect.Descriptor instead.
func (*EtcdServiceConfig) Descriptor() ([]byte, []int) {
	return file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *EtcdServiceConfig) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

var File_envoy_config_etcd_v3_etcd_cluster_proto protoreflect.FileDescriptor

var file_envoy_config_etcd_v3_etcd_cluster_proto_rawDesc = []byte{
	0x0a, 0x27, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x65,
	0x74, 0x63, 0x64, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x74, 0x63, 0x64, 0x5f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x2e, 0x76, 0x33, 0x1a,
	0x27, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x75, 0x64, 0x70, 0x61, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x11, 0x45, 0x74, 0x63, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4e, 0x0a, 0x0c, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x67, 0x72,
	0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x38, 0x0a, 0x22, 0x69, 0x6f, 0x2e,
	0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x2e, 0x76, 0x33, 0x42,
	0x10, 0x45, 0x74, 0x63, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescOnce sync.Once
	file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescData = file_envoy_config_etcd_v3_etcd_cluster_proto_rawDesc
)

func file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescGZIP() []byte {
	file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescOnce.Do(func() {
		file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescData)
	})
	return file_envoy_config_etcd_v3_etcd_cluster_proto_rawDescData
}

var file_envoy_config_etcd_v3_etcd_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_config_etcd_v3_etcd_cluster_proto_goTypes = []interface{}{
	(*EtcdServiceConfig)(nil), // 0: envoy.config.etcd.v3.EtcdServiceConfig
	(*v3.GrpcService)(nil),    // 1: envoy.config.core.v3.GrpcService
}
var file_envoy_config_etcd_v3_etcd_cluster_proto_depIdxs = []int32{
	1, // 0: envoy.config.etcd.v3.EtcdServiceConfig.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envoy_config_etcd_v3_etcd_cluster_proto_init() }
func file_envoy_config_etcd_v3_etcd_cluster_proto_init() {
	if File_envoy_config_etcd_v3_etcd_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_envoy_config_etcd_v3_etcd_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EtcdServiceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_envoy_config_etcd_v3_etcd_cluster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_config_etcd_v3_etcd_cluster_proto_goTypes,
		DependencyIndexes: file_envoy_config_etcd_v3_etcd_cluster_proto_depIdxs,
		MessageInfos:      file_envoy_config_etcd_v3_etcd_cluster_proto_msgTypes,
	}.Build()
	File_envoy_config_etcd_v3_etcd_cluster_proto = out.File
	file_envoy_config_etcd_v3_etcd_cluster_proto_rawDesc = nil
	file_envoy_config_etcd_v3_etcd_cluster_proto_goTypes = nil
	file_envoy_config_etcd_v3_etcd_cluster_proto_depIdxs = nil
}
